//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GEXVOC.Core.Informes {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("InformacionCanalDS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class InformacionCanalDS : global::System.Data.DataSet {
        
        private InformacionCanalDataTable tableInformacionCanal;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InformacionCanalDS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected InformacionCanalDS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["InformacionCanal"] != null)) {
                    base.Tables.Add(new InformacionCanalDataTable(ds.Tables["InformacionCanal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public InformacionCanalDataTable InformacionCanal {
            get {
                return this.tableInformacionCanal;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            InformacionCanalDS cln = ((InformacionCanalDS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["InformacionCanal"] != null)) {
                    base.Tables.Add(new InformacionCanalDataTable(ds.Tables["InformacionCanal"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableInformacionCanal = ((InformacionCanalDataTable)(base.Tables["InformacionCanal"]));
            if ((initTable == true)) {
                if ((this.tableInformacionCanal != null)) {
                    this.tableInformacionCanal.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "InformacionCanalDS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/RendimientoCanalDS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableInformacionCanal = new InformacionCanalDataTable();
            base.Tables.Add(this.tableInformacionCanal);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeInformacionCanal() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            InformacionCanalDS ds = new InformacionCanalDS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void InformacionCanalRowChangeEventHandler(object sender, InformacionCanalRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class InformacionCanalDataTable : global::System.Data.TypedTableBase<InformacionCanalRow> {
            
            private global::System.Data.DataColumn columnTipificacionFecha;
            
            private global::System.Data.DataColumn columnTipificacionDescConformacion;
            
            private global::System.Data.DataColumn columnTipificacionDescCategoria;
            
            private global::System.Data.DataColumn columnEngrasamientoFecha;
            
            private global::System.Data.DataColumn columnEngrasamientoDescTipo;
            
            private global::System.Data.DataColumn columnRendimientoFecha;
            
            private global::System.Data.DataColumn columnRendimientoRendimiento;
            
            private global::System.Data.DataColumn columnIdTipificacion;
            
            private global::System.Data.DataColumn columnIdEngrasamiento;
            
            private global::System.Data.DataColumn columnIdRendimiento;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalDataTable() {
                this.TableName = "InformacionCanal";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal InformacionCanalDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected InformacionCanalDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipificacionFechaColumn {
                get {
                    return this.columnTipificacionFecha;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipificacionDescConformacionColumn {
                get {
                    return this.columnTipificacionDescConformacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipificacionDescCategoriaColumn {
                get {
                    return this.columnTipificacionDescCategoria;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EngrasamientoFechaColumn {
                get {
                    return this.columnEngrasamientoFecha;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EngrasamientoDescTipoColumn {
                get {
                    return this.columnEngrasamientoDescTipo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RendimientoFechaColumn {
                get {
                    return this.columnRendimientoFecha;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RendimientoRendimientoColumn {
                get {
                    return this.columnRendimientoRendimiento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdTipificacionColumn {
                get {
                    return this.columnIdTipificacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdEngrasamientoColumn {
                get {
                    return this.columnIdEngrasamiento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdRendimientoColumn {
                get {
                    return this.columnIdRendimiento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalRow this[int index] {
                get {
                    return ((InformacionCanalRow)(this.Rows[index]));
                }
            }
            
            public event InformacionCanalRowChangeEventHandler InformacionCanalRowChanging;
            
            public event InformacionCanalRowChangeEventHandler InformacionCanalRowChanged;
            
            public event InformacionCanalRowChangeEventHandler InformacionCanalRowDeleting;
            
            public event InformacionCanalRowChangeEventHandler InformacionCanalRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddInformacionCanalRow(InformacionCanalRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalRow AddInformacionCanalRow(System.DateTime TipificacionFecha, string TipificacionDescConformacion, string TipificacionDescCategoria, System.DateTime EngrasamientoFecha, string EngrasamientoDescTipo, System.DateTime RendimientoFecha, decimal RendimientoRendimiento, int IdTipificacion, int IdEngrasamiento, int IdRendimiento) {
                InformacionCanalRow rowInformacionCanalRow = ((InformacionCanalRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TipificacionFecha,
                        TipificacionDescConformacion,
                        TipificacionDescCategoria,
                        EngrasamientoFecha,
                        EngrasamientoDescTipo,
                        RendimientoFecha,
                        RendimientoRendimiento,
                        IdTipificacion,
                        IdEngrasamiento,
                        IdRendimiento};
                rowInformacionCanalRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowInformacionCanalRow);
                return rowInformacionCanalRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                InformacionCanalDataTable cln = ((InformacionCanalDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new InformacionCanalDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnTipificacionFecha = base.Columns["TipificacionFecha"];
                this.columnTipificacionDescConformacion = base.Columns["TipificacionDescConformacion"];
                this.columnTipificacionDescCategoria = base.Columns["TipificacionDescCategoria"];
                this.columnEngrasamientoFecha = base.Columns["EngrasamientoFecha"];
                this.columnEngrasamientoDescTipo = base.Columns["EngrasamientoDescTipo"];
                this.columnRendimientoFecha = base.Columns["RendimientoFecha"];
                this.columnRendimientoRendimiento = base.Columns["RendimientoRendimiento"];
                this.columnIdTipificacion = base.Columns["IdTipificacion"];
                this.columnIdEngrasamiento = base.Columns["IdEngrasamiento"];
                this.columnIdRendimiento = base.Columns["IdRendimiento"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnTipificacionFecha = new global::System.Data.DataColumn("TipificacionFecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipificacionFecha);
                this.columnTipificacionDescConformacion = new global::System.Data.DataColumn("TipificacionDescConformacion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipificacionDescConformacion);
                this.columnTipificacionDescCategoria = new global::System.Data.DataColumn("TipificacionDescCategoria", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipificacionDescCategoria);
                this.columnEngrasamientoFecha = new global::System.Data.DataColumn("EngrasamientoFecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEngrasamientoFecha);
                this.columnEngrasamientoDescTipo = new global::System.Data.DataColumn("EngrasamientoDescTipo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEngrasamientoDescTipo);
                this.columnRendimientoFecha = new global::System.Data.DataColumn("RendimientoFecha", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRendimientoFecha);
                this.columnRendimientoRendimiento = new global::System.Data.DataColumn("RendimientoRendimiento", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRendimientoRendimiento);
                this.columnIdTipificacion = new global::System.Data.DataColumn("IdTipificacion", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdTipificacion);
                this.columnIdEngrasamiento = new global::System.Data.DataColumn("IdEngrasamiento", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdEngrasamiento);
                this.columnIdRendimiento = new global::System.Data.DataColumn("IdRendimiento", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdRendimiento);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalRow NewInformacionCanalRow() {
                return ((InformacionCanalRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new InformacionCanalRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(InformacionCanalRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.InformacionCanalRowChanged != null)) {
                    this.InformacionCanalRowChanged(this, new InformacionCanalRowChangeEvent(((InformacionCanalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.InformacionCanalRowChanging != null)) {
                    this.InformacionCanalRowChanging(this, new InformacionCanalRowChangeEvent(((InformacionCanalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.InformacionCanalRowDeleted != null)) {
                    this.InformacionCanalRowDeleted(this, new InformacionCanalRowChangeEvent(((InformacionCanalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.InformacionCanalRowDeleting != null)) {
                    this.InformacionCanalRowDeleting(this, new InformacionCanalRowChangeEvent(((InformacionCanalRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveInformacionCanalRow(InformacionCanalRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                InformacionCanalDS ds = new InformacionCanalDS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "InformacionCanalDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class InformacionCanalRow : global::System.Data.DataRow {
            
            private InformacionCanalDataTable tableInformacionCanal;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal InformacionCanalRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableInformacionCanal = ((InformacionCanalDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime TipificacionFecha {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableInformacionCanal.TipificacionFechaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TipificacionFecha\' de la tabla \'InformacionCanal\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.TipificacionFechaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TipificacionDescConformacion {
                get {
                    try {
                        return ((string)(this[this.tableInformacionCanal.TipificacionDescConformacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TipificacionDescConformacion\' de la tabla \'InformacionCan" +
                                "al\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.TipificacionDescConformacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TipificacionDescCategoria {
                get {
                    try {
                        return ((string)(this[this.tableInformacionCanal.TipificacionDescCategoriaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TipificacionDescCategoria\' de la tabla \'InformacionCanal\'" +
                                " es DBNull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.TipificacionDescCategoriaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime EngrasamientoFecha {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableInformacionCanal.EngrasamientoFechaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'EngrasamientoFecha\' de la tabla \'InformacionCanal\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.EngrasamientoFechaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EngrasamientoDescTipo {
                get {
                    try {
                        return ((string)(this[this.tableInformacionCanal.EngrasamientoDescTipoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'EngrasamientoDescTipo\' de la tabla \'InformacionCanal\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.EngrasamientoDescTipoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime RendimientoFecha {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableInformacionCanal.RendimientoFechaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RendimientoFecha\' de la tabla \'InformacionCanal\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.RendimientoFechaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal RendimientoRendimiento {
                get {
                    try {
                        return ((decimal)(this[this.tableInformacionCanal.RendimientoRendimientoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RendimientoRendimiento\' de la tabla \'InformacionCanal\' es" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.RendimientoRendimientoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdTipificacion {
                get {
                    try {
                        return ((int)(this[this.tableInformacionCanal.IdTipificacionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IdTipificacion\' de la tabla \'InformacionCanal\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.IdTipificacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdEngrasamiento {
                get {
                    try {
                        return ((int)(this[this.tableInformacionCanal.IdEngrasamientoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IdEngrasamiento\' de la tabla \'InformacionCanal\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.IdEngrasamientoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdRendimiento {
                get {
                    try {
                        return ((int)(this[this.tableInformacionCanal.IdRendimientoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IdRendimiento\' de la tabla \'InformacionCanal\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableInformacionCanal.IdRendimientoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipificacionFechaNull() {
                return this.IsNull(this.tableInformacionCanal.TipificacionFechaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipificacionFechaNull() {
                this[this.tableInformacionCanal.TipificacionFechaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipificacionDescConformacionNull() {
                return this.IsNull(this.tableInformacionCanal.TipificacionDescConformacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipificacionDescConformacionNull() {
                this[this.tableInformacionCanal.TipificacionDescConformacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipificacionDescCategoriaNull() {
                return this.IsNull(this.tableInformacionCanal.TipificacionDescCategoriaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipificacionDescCategoriaNull() {
                this[this.tableInformacionCanal.TipificacionDescCategoriaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEngrasamientoFechaNull() {
                return this.IsNull(this.tableInformacionCanal.EngrasamientoFechaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEngrasamientoFechaNull() {
                this[this.tableInformacionCanal.EngrasamientoFechaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEngrasamientoDescTipoNull() {
                return this.IsNull(this.tableInformacionCanal.EngrasamientoDescTipoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEngrasamientoDescTipoNull() {
                this[this.tableInformacionCanal.EngrasamientoDescTipoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRendimientoFechaNull() {
                return this.IsNull(this.tableInformacionCanal.RendimientoFechaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRendimientoFechaNull() {
                this[this.tableInformacionCanal.RendimientoFechaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRendimientoRendimientoNull() {
                return this.IsNull(this.tableInformacionCanal.RendimientoRendimientoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRendimientoRendimientoNull() {
                this[this.tableInformacionCanal.RendimientoRendimientoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdTipificacionNull() {
                return this.IsNull(this.tableInformacionCanal.IdTipificacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdTipificacionNull() {
                this[this.tableInformacionCanal.IdTipificacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdEngrasamientoNull() {
                return this.IsNull(this.tableInformacionCanal.IdEngrasamientoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdEngrasamientoNull() {
                this[this.tableInformacionCanal.IdEngrasamientoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdRendimientoNull() {
                return this.IsNull(this.tableInformacionCanal.IdRendimientoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdRendimientoNull() {
                this[this.tableInformacionCanal.IdRendimientoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class InformacionCanalRowChangeEvent : global::System.EventArgs {
            
            private InformacionCanalRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalRowChangeEvent(InformacionCanalRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InformacionCanalRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591