IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='_BÁSICO')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (null,'_BÁSICO')	


--INSERTAR ELEMENTOS DEPENDIENTES DE (BÁSICO)
----OBTENGO EL IDENTIFICADOR DEL MÓDULO BÁSICO PARA PODER SEGUIR HACIENDO LAS INSERCIONES.
declare @IdBasico int;
SELECT @IdBasico=Id FROM Modulo WHERE Descripcion='_BÁSICO';


IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA ALIMENTACIÓN')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA ALIMENTACIÓN')	
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA SANIDAD')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA SANIDAD')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA ECONOMÍA')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA ECONOMÍA')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA FINCAS')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA FINCAS')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA VADEMÉCUM')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA VADEMÉCUM')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA GENÉTICA')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA GENÉTICA')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA GENEALOGÍA')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA GENEALOGÍA')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA AGENDA')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA AGENDA')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA ALERTAS')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA ALERTAS')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA REPRODUCCIÓN')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA REPRODUCCIÓN')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA TRAZABILIDAD')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA TRAZABILIDAD')

--INSERTAR ELEMENTOS DEPENDIENTES DE (TRAZABILIDAD)
----OBTENGO EL IDENTIFICADOR DEL MÓDULO TRAZABILIDAD PARA PODER INSERTAR EL MÓDULO APPCC (DEPENDIENTE).
declare @IdTrazabilidad int;
SELECT @IdTrazabilidad=Id FROM Modulo WHERE Descripcion='SUBSISTEMA TRAZABILIDAD';
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA APPCC')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdTrazabilidad,'SUBSISTEMA APPCC')

--INSERTAR ELEMENTOS DEPENDIENTES DE (REPRODUCCIÓN)
----OBTENGO EL IDENTIFICADOR DEL MÓDULO REPRODUCCION PARA PODER INSERTAR SUS MÓDULOS DEPENDIENTES: PROD. CARNE Y LECHE
declare @IdReproduccion int;
SELECT @IdReproduccion=Id FROM Modulo WHERE Descripcion='SUBSISTEMA REPRODUCCIÓN';

IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA PRODUCCIÓN LECHE')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA PRODUCCIÓN LECHE')
IF NOT EXISTS (SELECT * FROM Modulo WHERE Descripcion='SUBSISTEMA PRODUCCIÓN CARNE')	
	INSERT INTO [Modulo] ([IdPrincipal],[Descripcion]) VALUES (@IdBasico,'SUBSISTEMA PRODUCCIÓN CARNE') 